#!/usr/bin/env bash

set -efu

function main {
  set -x
  block compile virtualenv27
  (set +f; cd bin && ln -nfs \
    ../vendor/virtualenv/bin/ansible \
    ../vendor/virtualenv/bin/ansible-* \
    .)
}

main "$@"
